#!/usr/bin/env bash
set -euo pipefail

dir=$(cd -- "$(dirname -- "$0")" && pwd)
config=${XDG_CONFIG_HOME:-$HOME/.config}/hypr/workspace-displays.json
cache=${XDG_CACHE_HOME:-$HOME/.cache}/hypr
layout=$cache/workspace-display-layout.tsv
generated=$dir/workspace-monitors.generated.conf
mkdir -p "$cache"

exec 9>"$cache/workspace-monitor-apply.lock"
flock -n 9 || exit 0

monitors_json=$(hyprctl -j monitors all)
mapfile -t detected < <(
  jq -r '[.[] | select((.disabled // false) == false and (.width // 0) > 0)]
         | sort_by(.x, .y, .name) | .[].name' <<<"$monitors_json"
)
(( ${#detected[@]} > 0 )) || exit 0

declare -A connected=() used=()
for monitor in "${detected[@]}"; do connected["$monitor"]=1; done

preferred_main=''
configured=()
if jq -e '.version == 1 and (.order | type == "array")' "$config" >/dev/null 2>&1; then
  preferred_main=$(jq -r '.main // empty' "$config")
  mapfile -t configured < <(jq -r '.order[] | strings' "$config")
fi

ordered=()
for monitor in "${configured[@]}"; do
  if [[ -n ${connected[$monitor]:-} && -z ${used[$monitor]:-} ]]; then
    ordered+=("$monitor")
    used["$monitor"]=1
  fi
done
for monitor in "${detected[@]}"; do
  if [[ -z ${used[$monitor]:-} ]]; then
    ordered+=("$monitor")
    used["$monitor"]=1
  fi
done

focused=$(jq -r '.[] | select(.focused == true) | .name' <<<"$monitors_json" | head -n1)
if [[ -z $preferred_main || -z ${connected[$preferred_main]:-} ]]; then
  preferred_main=${focused:-${ordered[0]}}
fi

managed_count=${#ordered[@]}
(( managed_count > 5 )) && managed_count=5

main_index=-1
for ((i=0; i<managed_count; ++i)); do
  [[ ${ordered[i]} == "$preferred_main" ]] && main_index=$i
done
if (( main_index < 0 )); then
  for ((i=0; i<${#ordered[@]}; ++i)); do
    if [[ ${ordered[i]} == "$preferred_main" ]]; then
      displaced=${ordered[managed_count-1]}
      ordered[managed_count-1]=$preferred_main
      ordered[i]=$displaced
      main_index=$((managed_count-1))
      break
    fi
  done
fi
(( main_index < 0 )) && main_index=0

mapfile -t partition_plan < <(
  "$HOME/.local/bin/workspace-display-manager" --print-plan-tsv "$managed_count" "$main_index"
)
(( ${#partition_plan[@]} == managed_count )) || exit 1

layout_tmp=$layout.tmp
generated_tmp=$generated.tmp
printf '# index\tmonitor\tfirst-sub\tlast-sub\tmain\n' > "$layout_tmp"
printf '# Generated by workspace_monitor_apply.sh. Do not edit.\n' > "$generated_tmp"

for ((i=0; i<managed_count; ++i)); do
  monitor=${ordered[i]}
  IFS=$'\t' read -r plan_index first last <<<"${partition_plan[i]}"
  (( plan_index == i )) || exit 1
  is_main=0
  (( i == main_index )) && is_main=1
  printf '%d\t%s\t%d\t%d\t%d\n' "$i" "$monitor" "$first" "$last" "$is_main" >> "$layout_tmp"
  for ((main=1; main<=10; ++main)); do
    for ((sub=first; sub<=last; ++sub)); do
      printf 'workspace = %d, monitor:%s\n' "$((main * 10 + sub))" "$monitor" >> "$generated_tmp"
    done
  done
done
mv "$layout_tmp" "$layout"

changed=1
if [[ -r $generated ]] && cmp -s "$generated_tmp" "$generated"; then
  changed=0
  rm -f "$generated_tmp"
else
  mv "$generated_tmp" "$generated"
fi

source "$dir/workspace_grid_lib.sh"
active_id=$(hyprctl activeworkspace -j | jq -r '.id // 0')
if [[ $active_id =~ ^[0-9]+$ ]] && (( active_id >= 11 && active_id <= 110 )); then
  active_main=$(( (active_id - 1) / 10 ))
  active_sub=$(( (active_id - 1) % 10 + 1 ))
else
  active_main=$(grid_saved_axis /tmp/hypr_main_workspace 1)
  active_sub=''
fi
if [[ -n $focused && -n $active_sub ]] && grid_layout_for_monitor "$focused"; then
  if (( active_sub >= GRID_RANGE_FIRST && active_sub <= GRID_RANGE_LAST )); then
    grid_store_sub "$active_main" "$focused" "$active_sub"
  fi
fi

if (( changed )); then hyprctl reload >/dev/null; fi

mapfile -t existing < <(hyprctl -j workspaces | jq -r '.[].id | select(. >= 11 and . <= 110)')
for id in "${existing[@]}"; do
  sub=$(( (id - 1) % 10 + 1 ))
  if grid_layout_for_sub "$sub"; then
    hyprctl dispatch moveworkspacetomonitor "$id $GRID_MONITOR" >/dev/null 2>&1 || true
  fi
done

grid_switch_main "$active_main"
